language: node_js
node_js:
  - '7'

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    - DOCKER_ORG=builditdigital
    - DOCKER_REPO=bookit-web
    # Docker Login
    - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
    - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=
    - AWS_DEFAULT_REGION=us-east-1
    - S3_BUCKET_BASE=rig.buildit.bookit.int
    - BOOKITURI=https://int-bookit-web.buildit.tools
    # This identifies what namespace to pull configuration from
    - INT_ENV_NAME=int
    - ECS_REPO=buildit-bookit-web-ecr-repo
    - INT_ECS_CLUSTER=buildit-bookit-int-ECSCluster
    - INT_ECS_SERVICE=buildit-bookit-int-app-BookitWebService-B6F7GJAV94CC-Service-1PZ74XVAO63TI
    - STG_ECS_CLUSTER=buildit-bookit-stg-ECSCluster
    - STG_ECS_SERVICE=buildit-bookit-stg-app-BookitWebService-1CTDRV2T4B00Z-Service-QJK7Q44XFNLI
    # AWS_ACCESS_KEY_ID (CloudFormation stack IAM account)
    - secure: YSNTg7KN5N2iuO5iwClPbvz7ZhKHvzJc4RiIydY2F9/QMIGCjGQRECi30cOg06yo0xCb/FIzlZw3hK7z0V7TSA7wzhwVyDLW1TO75jbs0MwBDoSt953bsii59vCXC88rjVqjMQISOKIU4h9KXs5cvsQzYDlYIQiWTM2W2Y3GLEoLg7q1/82EhrzA1GXWoovEyIaG9UU1wrsnbMsaydT0pW9AbwSRmYfWkgji9mBea3SSxDYMM+6kubb+gpQTC6PW2Mg0DAnlxNnKvNP1WLzmb+c06AKDd7kPOh40Cq1Dp8pqroIyrQc7Fq8IUKpawenVOHgPOyBIOgMP/HNhP2OewInLHPKBF3CP6PLQOTgI76njfUPPnY9jVCqLFW9EBvEkQaXGM5xf90fXaEgdXKyamR7Mz44HhjIE+I89C+c6wb9p1N8SIe22RRTg9jdR/2BXl/NotXNuHMhUUhcYhFXHAqUhfIrWQp2qDmw5044nw09ihhYcqHva1QrlMEXqJKS4a3LIMjaS/mbnSkmi1Vetl7Ko1P95JXfrpH6E+R8aAV9JyXBKppWHJTl2qtScLdpyTIYBdpg+4ypHF4ya46vX3Q8SzPo7Se4M1n+rpXbjnEoZQO4L5hEDTZ1bPpgtqbqYF9VZfoTYPZzoskUtJFPlxBwg23CWBHmOXp3ihwT2WrM=
    # AWS_SECRET_ACCESS_KEY (CloudFormation stack IAM account)
    - secure: MAN/LoGLB20hFK0grWNiSnH/ttpew5q5b4n/MRTjCXp/19bezDUT9M3U4fy7GCXydNCYhwSD4v+0/7Y2zNM568vEOFbIu3GoorFt74dMgIkg88jvWDdvPhieHySyKhRGZwVAqwWJLPlTYzQC9NJmguwuIaRrreNEngf6PNj1d27+JAE2q+8H8LN1b5bUd0+egXHqr7Tx/Sr/MmeCr+piGoAY7G/HWQJqJCE0qnxAmvvluIOqcojbD9dKAgtbkzYTnF6bBCL55rQoeiTGgvQu/IfX1n4ICzSPhavg3H13hmaiGN6/hOeDygiSJY7zIF16b2BgBWNR+mm0uFvpiP5nH9PVWOqe8tgWsvKRXFL3/C98laQqed9Di/woIc1rsxi//0JX2mn52kREsAc/cT0WPSiEfftYfrYCRaQE/+MHyzxt5qA8tAl3Wr4UytIOXFs4EdmgK/A5dC94YRx7lQ2IVC0YD50JhHY0806bNZSVKUMGpn1hdh9Qs8smkatBKBN1/O5dWQ4neoBF+NIXQXe8F76doymgTxSSUbQxNQxcmp39s+H1/YBveYfb+4mTq5/SZx6crAPUu3KD2F+ezB4ZpOAkBTlM0vFD1p7S2zppRQztyvGVDja+3oSBEPSPeloSWke1D7hjIl7X3O/Dd6DpmWHV5idMpdRRpBk9mlqZLPk=

install:
  - yarn

script:
  - yarn lint
  - yarn test:unit -- --colors --ci --silent
  - npm rebuild node-sass
  - if [[ -z "$TRAVIS_PULL_REQUEST" || $TRAVIS_PULL_REQUEST == "false" ]] && [[ -z "$TRAVIS_BRANCH" || $TRAVIS_BRANCH == "master" ]]; then ./scripts/run-ci-cd.sh; fi

after_success:
  - ./scripts/run-coveralls.sh

notifications:
  slack:
    rooms:
      - secure: "W6ngcqgzcmk6Vn/+q+D7Yvk74unBtEn19W9jye4HcKPh6L23S8PgKNop7ANRf/msmlYZkmxPhT3bPB+nrYiIKHXbraelOtsjVVssf0GfpjN95tT6IQlKSD9HASWQaLDpqY6OtNL5zRf7l1dkou6BD+vUjOs27oLSnGJtJguSUAWiJ23176P0LkfFOhpgHrduDQE8pP5k/lmx3zZX4gdT2Zv8OHzqMhSJEjDvIL6OI9EAbP8atkVNTYKDeJmuiBRuGp+St3Pf9dv2qBK88eixLDTdxS0jmtPQHBgqPRon3ess3VoOnognHhSg+4YAcr6na9e0kXbBnADnQcK1sDYSiLTvqAqJ4usIwxVRmGsBawNmyXr4zMieJ7gt1pj/CgNap5rS/47bb+hAQWwSLUEVntwXEqvoOEBGUHEFVW5oD2zbor95tqdTwi51GCgjqVGmkNar27X7sB5/qQb3iaeftUBcWk5E4LrDTnhFzA3YiaoHhwtzbKed4Fht/x1oCV3ImAaOO4MCPa4d05iclCU7begU3fdOWMLkap4sZvSVccD6rt8jjfBa8pTEt81QW1Xu2PQn1oVIdLlheQX3O7FiZ9gA9C4fbfDfMlwNnTRWNitKJFn7VM7pNaqYA3UpNN370umohWWc/0xEcQlHa723sQDUSixrhm+RQtcr2tKYALM="
    template:
      - "%{commit_message}"
      - ":cat: :sparkles: :cat:  :sparkles:  :cat: :sparkles: :cat:"
      - ":wrench: <%{build_url}|#%{build_number}>"
      - ":eye: (<%{compare_url}|%{commit}>)"
      - "%{repository_name}@%{branch} by %{author}"
