# Default values for synapse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: builditdigital/synapse
  tag: latest
  pullPolicy: Always
service:
  name: synapse
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  hostName:
resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 30m
    memory: 32Mi
app:
  eolasUrl: http://eolas-svc/
  noauth: true
