sudo: required

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

  artifacts:
    debug: true
    paths:
      - ./screenshots
    target_paths: $TRAVIS_BUILD_NUMBER
    bucket: icarus-build-reports
    s3_region: us-east-1


language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
env:  
  global:
    - SLS_DEBUG=true
    - DISPLAY=:99.0 

before_install:
  - yarn global add serverless
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
 
install:
  - ./scripts/install-sls.sh
  - ./scripts/install-fe.sh

before_script: 
  - source scripts/init-env.sh
   
script: 
  - ./scripts/test-sls.sh &&
    ./scripts/build-fe.sh &&
    ./scripts/deploy-sls.sh
  - 'if [ "$SKIP_E2E" != "true" ]; then bash ./scripts/test-e2e.sh; fi'
