region="us-east-1"
route53-zone-id="Z1JCR8Z8SKICKR"
keypair="bookit"
travis_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzKXYaUdyDgxiCNqXayPk0fX4D2VjMZxPANvyQFsghIZZ8DaOsaOF5Ek5H7AcsetYOl/Y+sZscfHHKgBqhfsjdBuL5e/bL+U/QxggbdGDeYWADrr18zg3PqSjWF3JtyOZJNgnAVc5Ha/piGyYVl5UKYhDN+Rai6y+FsZol4S1YUvbU/M840N6gh6rbsZ9TiuAaBTBz/0CBAUrPqsNW+U6+AigJrGaVavfG2VkMBA6C/+XQSwytOlHta+uduwLxsjUAr3kLayJEnOTX/TvjaVdWwNzLE2G9nPuyO5gkw4n2YpbsLKcMOCEDvXndSV8O+FdRVFACjtAsd4QOEIcbwB85 travis@github"
