language: java
env:
  global:
  - GIT_USERNAME=Travis CI
  - GIT_EMAIL=builds@travis-ci.com
  - TAG=$(./pipeline.sh getProperty version gradle.properties)
  - RELEASE_FILE=build/libs/config-fetcher-$TAG.jar
  - RELEASE_POM=build/pom.xml
  - LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
  - CD_COMMIT_MESSAGE='[travis] Bump version number'
  - GITHUB_USER=dermotmburke
  - secure: Cff075+/T5qiEuW+kwQpNiPzw25XtMky8hA708AL6JQpNoeWEWQBMomeHo4qwxOZoeErx75ddTFTePsbm9iGKojs3FflibjkvwuADnMcm4HDyJ6mYLz9P57tQshW5OaPJsaN948p80aRpSeKrwdydidyr3y5dGBv2+sc9z4/AG/VHKLdk+x9meL60bNfDIl6lYVYsEJaun4aIMDwMQOok/W9mT0zSnbCEXtVBGsK/8WAp3XvZ2+F9y6+KLaAV3VLBKF2nm+ofHH85dHo6ttSVFpdfnwXEl1hoiBSLGd11J9T4fGD4JFHLM8Vm/k/KdeXTvKSywgHS2efP74WLnL8NjwHwkyAv7RsKbtGRrNWgCEwHd6a+tOLwpsjr4D0MLj4mVn4OSY3vssoYSmR23fxcVMyPbceUYC4W28qzNdWdpNbv4hQeau64tXAwbJw8OAOPA0h7xoOjRKR84ozhSRh52i7z0gm5TfttoTR3EeY+lRBxI7lRjlCJc0JYNVwkHmgYd8H5MNMpyhIf/pspmM5ruzy/dzW5GVNY9MwpczK9VVbhL5fS46IRQXb/TH6aULFSN2flgvPx9JBjxVJMufNvGn+K2q/od38C/PbEtMudeiy6pGCE7aM3AIgOM2BQlUkDbewo4VmNXY4COq+gJlJ0kiGOUqAXEu+37iBuZwoJGM=
  - secure: AaD+MaUynuaycObdT3HRExqDnY8RWNu1prqa2LD0KN5lUrDeMFq9TbUofnbySMJCDPBnd99VJqaGLQ1uGgAg8rG/6AWZEMm40yHcRD9MX521CBFc5pM8aSGjRv0ltiKiQOqR41GgyqLJURYj1vXGI/vg74qPaaVq3w4XesumQsIgHvZaRSSTtWWs1QVj6ADTeA6INoD3OMb/nhVDVU+5rHJAs//LCj0nl1s0cOo+sJtKcNRuOL9ufQSPlogZbOIy+z1We4n0YtcrbILIVVbByWLRM4tPDUC2fNmOWnabUliNmZyXHB1j/cx4W692a52EDyOsvR+PKmIf33EMVo6rA47VV6EAqCTgizBKYcqRNqp/ICMfYFIxuUzdwui3/Xi75j2n2X9fMnL0FFPbNS4AOZ3G5DikmVT48wyn+jsBfZEFOVMEieUrZczHwbWXBfnL14klUod7DGvkrBE1n8vUzkAe/hNXJZyXt9NQveU7hnW0gAGLho1owQr5iHMaS7gRKIvk0eCZ1DNDaQGHwwj1bAmp5YfbVTeleHPkHt2OMbTiFFcnTX9U5FXsPeW8LFssCwGgTbGFCleB7QJjeyJ1dIzop8m8aSZtaJpzZsGQOmNnN0lcWsz1MUGvWebmubI6iwLUgisBli0Ux4bRqlBECo3BX8RtrkwFKEhKUxEY3YQ=
script:
- ./pipeline.sh build
before_deploy:
- ./pipeline.sh tag
deploy:
  - provider: script
    script: gradle bintrayUpload -PbintrayUser=buildit -PbintrayKey=$BINTRAY_TOKEN -PdryRun=false
    skip_cleanup: true
    on:
      branch: master
      tags: false
      condition: '"${LAST_COMMIT_MESSAGE}" != "${CD_COMMIT_MESSAGE}"'
after_deploy:
- ./pipeline.sh bump