AWSTemplateFormatVersion: "2010-09-09"
Description: > 
  DNS entries for Static website infra.
  Single environment. 
  Creates a records on Route53.
  THE ROUTE53 ZONE MUST ALREADY EXIST.
  THIS STACKS DEPENDS ON A WEBSITE-INFRA STACK.

Parameters:

  WebsiteInfraStackName:
    Type: String
    Description: Name of the CloudFormation stack creating the website infrastructure


Resources:
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: 
        { "Fn::Join" : [ '', 
          [ { "Fn::ImportValue" : { "Fn::Sub": "${WebsiteInfraStackName}-ZoneName" } }, '.' ]
        ] }
      Name: 
        { "Fn::Join" : [ '', 
          [ { "Fn::ImportValue" : { "Fn::Sub": "${WebsiteInfraStackName}-WebsiteDnsName" } }, '.' ]
        ] }
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Fixed value for CloudFront
        DNSName:
          { "Fn::Join" : [ '', 
            [ { "Fn::ImportValue" : { "Fn::Sub": "${WebsiteInfraStackName}-DistributionDomainName" } }, '.' ]
          ] }

Outputs:
  DnsZoneName:
    Description: 'DNS Zone'
    Value: 
      Fn::ImportValue:
        !Sub "${WebsiteInfraStackName}-ZoneName"
    Export:
      Name: !Sub "${AWS::StackName}-ZoneName"

  WebsiteDnsNamer:
    Description: 'Website FQ DNS name'
    Value: 
      Fn::ImportValue:
        !Sub "${WebsiteInfraStackName}-WebsiteDnsName"
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteDnsName"    